name: Code Linter

run-name: Check code for proper formatting

on: 
    push:
        branches: dev

jobs:
    Lint-The-Code:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Lint the code
              uses: super-linter/super-linter@v7.2.1
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  VALIDATE_JAVASCRIPT_PRETTIER: true

            - name: Clean the repo
              if: success()
              run: git clean -fdx
              
            - name: Create Pull Request if Lint Passes
              if: success()
              uses: peter-evans/create-pull-request@v7
              with:
                branch: dev
                title: Merge Dev into Main
                body: "Automated PR: Dev branch passed lint checks and is ready to merge"
                labels: automation, lint-passed
                base: main-branch
                delete-branch: false

            - name: Comment when Lint fails
              if: failure()
              run: echo "Lint failed"
